# Example alertmanager.yml configuration
#
# See https://prometheus.io/docs/alerting/configuration/ for Alertmanager configuration syntax and built-in receivers.
# Currently, these include email, HipChat, PagerDuty, OpsGenie, Slack, VictorOps, and WeChat.

# If you need to send to a target that isn't built into Alertmanager, consider configuring a webhook_configs below and
# using an online service such as https://built.io or instead running a bot container to receive
# and relay alerts. swarmstack provides an Errbot Docker image for this purpose, which currently also supports Cisco
# Webex Teams, IRC, Telegram Messenger, and XMPP/Jabber services. Other backends, such CampFire, Discord, Gitter, Matrix,
# Mattermost, Matrix, Microsoft Bot Framework, Skype, Tox, VK, Zulip and others are supported through the Errbot community.
# If you want to run a bot to relay alerts, see:
#
# https://github.com/swarmstack/errbot-docker

route:

  group_by: ['alertname']
  group_wait: 45s
  group_interval: 10m
  repeat_interval: 6h
  receiver: 'first-responders'

receivers:

  - name: 'first-responders'

#    email_configs:
#      - to: 'user@example.com'
#        send_resolved: false
#        from: 'no-reply@example.com'
#        smarthost: 'outbound.example.com:25'

#    webhook_configs:
#      - send_resolved: false
#        url: http://errbot:3141/alerrt/username/domain.com/
